title: Kabanero
email: ajlohr@us.ibm.com
description: >
  Kabanero delivers new and existing middleware tools to modernize your cloud journey.
baseurl: ""
url: "https://kabanero.io"
twitter_url: https://twitter.com/Kabaneroio
github_url:  https://github.com/kabanero-io
stackoverflow_url: https://stackoverflow.com/questions/tagged/kabanero
slack_url: https://ibm-cloud-tech.slack.com/messages/CJZCYTD0Q
slack_invite_url: https://slack-invite-ibm-cloud-tech.mybluemix.net/
twitter_username: KabaneroIO
github_username: kabanero-io

asciidoctor:
  base_dir: :docdir
  safe: 0
  attributes:
    - icons=font
    - source-highlighter=coderay
    - coderay-linenums-mode=inline
    - coderay-linenums=true
    - coderay-css=class
    - allow-uri-read

markdown: kramdown

assets:
  compression: true

env: production

# jekyll-assets will compress our js and css
jekyll-minifier:
  compress_javascript: false
  compress_css: false

plugins:
  - jekyll-feed
  - jekyll-asciidoc
  - jekyll-assets
  - ol-asciidoc
  - jekyll-minifier
  - jekyll-polyglot

exclude: [vendor, docs/templates]

languages: ["en"]
# We currently dont have translation for all these languages so we comment them out.
# ["es", "de", "fr", "it", "ja", "ko","pt-BR", "zh-CN", "zh-TW"]

default_lang: "en"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true

site_custom:
  index:
    docs_url: /docs
  header:
    title_logo: /img/Kabanero_white_title_text.svg
    header_logo: /img/Kabanero_Logo_White_Text.png