language: minimal

before_install:
  - docker pull  kabanerobuild/website-travis:latest 

install:
  - docker build --cache-from  kabanerobuild/website-travis:latest -t landing-travis -f travis/Dockerfile .

stages:
  - name: Running tests
    if: (type IN (pull_request))

jobs:
  include:
    - stage: "Running tests"
      name: "Running lint testing and building website with Jekyll"
      script:
        - ./travis/docker_run.sh "./node_modules/.bin/eslint src/main/content/_assets/js/*.js"
        - ./travis/docker_run.sh "Xvfb :99 & ./scripts/build_jekyll_maven.sh && mvn liberty:install-feature && mvn verify"
